edition = "2021"
unstable_features = true
condense_wildcard_suffixes = true
empty_item_single_line = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_generated_files = false
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
spaces_around_ranges = true
wrap_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
tab_spaces = 2
max_width = 80
imports_indent = "Visual"
imports_layout = "Horizontal"
# indent_style = "Visual"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
