[package]
name = "mlcts"
version = "0.1.0"
edition = "2021"
license = "MIT OR CC-BY-NC-SA-4.0"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
csv = "1.3.0"
lazy_static = "1.5.0"
