[config]
default_to_workspace = false

[tasks.myg2p-mlcts]
command = "cargo"
args = ["run", "-p", "mlcts_dev_tools", "--bin", "mk-myg2p-mlcts", "${@}"]

[tasks.tokenizer-inputs]
command = "cargo"
args = ["run", "-p", "mlcts_dev_tools", "--bin", "mk-tokenizer-inputs", "${@}"]
dependencies = ["myg2p-mlcts"]

[tasks.tokenizer-test-gen]
command = "cargo"
args = ["run", "-p", "mlcts_dev_tools", "--bin", "gen-tokenizer-tests", "${@}"]
dependencies = ["tokenizer-inputs"]

[tasks.test-tokenizer]
command = "cargo"
args = ["test", "-p", "mlcts_tokenizer", "${@}"]
dependencies = ["tokenizer-test-gen"]

[tasks.test]
command = "cargo"
args = ["test", "${@}"]
dependencies = ["tokenizer-test-gen"]
