[package]
name = "mlcts_proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
csv = "1.3.0"
proc-macro2 = "1.0.87"
quote = "1.0.37"
syn = "2.0.79"
mlcts_core = { path = "../mlcts_core" }
